/**
 * GENERATED FILE — do not edit.
 *
 * Source of truth: `apps/server/src/nomior/seed/scenario.ts` (the same data
 * `pnpm nomior:seed` writes into the database).
 * Regenerate with: `pnpm --filter t3 nomior:gen-fixtures`.
 *
 * Times are offsets, not instants: the scenario is dated, but the panels must
 * look alive whenever they are opened. `fixtures.ts` resolves them against
 * the current week.
 *
 * No imports on purpose: this module is plain data, so the panels can render
 * from it with nothing behind them and any tool can read it.
 */

export const generatedFixtures = {
  reviewJobs: [
    {
      id: "rev-101",
      repo: "nomior-dev/nomior-code",
      pullRequestNumber: 412,
      pullRequestTitle: "feat(server): context broker retrieval pipeline",
      pullRequestState: "open",
      riskTier: "high",
      status: "queue",
      verdict: null,
      severityCounts: {
        blocker: 0,
        major: 0,
        minor: 0,
      },
      manualReviewRequested: false,
      headSha: "4f2a9c1",
      createdAgoHours: 0.5,
      updatedAgoHours: 0.4,
    },
    {
      id: "rev-102",
      repo: "nomior-dev/nomior-invest",
      pullRequestNumber: 388,
      pullRequestTitle: "fix(pipeline): dedupe filings ingest cursors",
      pullRequestState: "open",
      riskTier: "medium",
      status: "queue",
      verdict: null,
      severityCounts: {
        blocker: 0,
        major: 0,
        minor: 0,
      },
      manualReviewRequested: false,
      headSha: "8b13e7d",
      createdAgoHours: 1.33,
      updatedAgoHours: 1.2,
    },
    {
      id: "rev-103",
      repo: "nomior-dev/nomior-code",
      pullRequestNumber: 409,
      pullRequestTitle: "feat(web): instances panel scheduler surface",
      pullRequestState: "open",
      riskTier: "medium",
      status: "reviewing",
      verdict: null,
      severityCounts: {
        blocker: 0,
        major: 1,
        minor: 2,
      },
      manualReviewRequested: false,
      headSha: "c07d4aa",
      createdAgoHours: 0.67,
      updatedAgoHours: 0.1,
    },
    {
      id: "rev-104",
      repo: "nomior-dev/nomior-music",
      pullRequestNumber: 96,
      pullRequestTitle: "feat(catalog): ISRC dedupe pass over delivery feeds",
      pullRequestState: "open",
      riskTier: "high",
      status: "waiting-external",
      verdict: null,
      severityCounts: {
        blocker: 1,
        major: 1,
        minor: 0,
      },
      manualReviewRequested: true,
      headSha: "51ff902",
      createdAgoHours: 3.5,
      updatedAgoHours: 3,
    },
    {
      id: "rev-105",
      repo: "nomior-dev/nomior-code",
      pullRequestNumber: 401,
      pullRequestTitle: "chore(fork): daily upstream sync",
      pullRequestState: "open",
      riskTier: "low",
      status: "approved",
      verdict: "approved",
      severityCounts: {
        blocker: 0,
        major: 0,
        minor: 1,
      },
      manualReviewRequested: false,
      headSha: "a91c3f5",
      createdAgoHours: 6.75,
      updatedAgoHours: 6,
    },
    {
      id: "rev-106",
      repo: "nomior-dev/nomior-invest",
      pullRequestNumber: 379,
      pullRequestTitle: "feat(agents): unattended portfolio rebalancer",
      pullRequestState: "open",
      riskTier: "high",
      status: "not-approved",
      verdict: "not-approved",
      severityCounts: {
        blocker: 2,
        major: 3,
        minor: 1,
      },
      manualReviewRequested: false,
      headSha: "6d2b840",
      createdAgoHours: 27.83,
      updatedAgoHours: 26,
    },
    {
      id: "rev-107",
      repo: "nomior-dev/nomior-code",
      pullRequestNumber: 396,
      pullRequestTitle: "fix(web): calendar header follows the grid",
      pullRequestState: "merged",
      riskTier: "low",
      status: "approved",
      verdict: "approved",
      severityCounts: {
        blocker: 0,
        major: 0,
        minor: 0,
      },
      manualReviewRequested: false,
      headSha: "c40f118",
      createdAgoHours: 45.92,
      updatedAgoHours: 45.2,
    },
    {
      id: "rev-108",
      repo: "nomior-dev/nomior-music",
      pullRequestNumber: 91,
      pullRequestTitle: "spike(catalog): MusicBrainz as an ISRC backfill source",
      pullRequestState: "closed",
      riskTier: "medium",
      status: "waiting-external",
      verdict: null,
      severityCounts: {
        blocker: 0,
        major: 0,
        minor: 1,
      },
      manualReviewRequested: true,
      headSha: "0e7ab52",
      createdAgoHours: 65,
      updatedAgoHours: 64.33,
    },
  ],
  calendarAccounts: [
    {
      id: "google-work",
      email: "work@nomior.example",
      colorIndex: 0,
    },
    {
      id: "google-personal",
      email: "personal@gmail.example",
      colorIndex: 1,
    },
  ],
  calendarEvents: [
    {
      id: "evt-standup-0824",
      accountId: "google-work",
      title: "Daily standup",
      dayOffset: 0,
      startHour: 9,
      startMinute: 30,
      durationMinutes: 15,
      recurringSeriesId: "series-daily-standup",
      meeting: {
        meetingId: "meet-standup-0824",
        hasTranscript: true,
        hasNotes: true,
      },
    },
    {
      id: "evt-standup-0825",
      accountId: "google-work",
      title: "Daily standup",
      dayOffset: 1,
      startHour: 9,
      startMinute: 30,
      durationMinutes: 15,
      recurringSeriesId: "series-daily-standup",
      meeting: {
        meetingId: "meet-standup-0825",
        hasTranscript: true,
        hasNotes: true,
      },
    },
    {
      id: "evt-standup-0826",
      accountId: "google-work",
      title: "Daily standup",
      dayOffset: 2,
      startHour: 9,
      startMinute: 30,
      durationMinutes: 15,
      recurringSeriesId: "series-daily-standup",
      meeting: null,
    },
    {
      id: "evt-standup-0827",
      accountId: "google-work",
      title: "Daily standup",
      dayOffset: 3,
      startHour: 9,
      startMinute: 30,
      durationMinutes: 15,
      recurringSeriesId: "series-daily-standup",
      meeting: {
        meetingId: "meet-standup-0827",
        hasTranscript: true,
        hasNotes: true,
      },
    },
    {
      id: "evt-review-engine-0825",
      accountId: "google-work",
      title: "Review engine deep dive",
      dayOffset: 1,
      startHour: 14,
      startMinute: 0,
      durationMinutes: 90,
      recurringSeriesId: null,
      meeting: {
        meetingId: "meet-review-engine-0825",
        hasTranscript: true,
        hasNotes: true,
      },
    },
    {
      id: "evt-anarlog-0826",
      accountId: "google-work",
      title: "Anarlog connector integration",
      dayOffset: 2,
      startHour: 16,
      startMinute: 0,
      durationMinutes: 60,
      recurringSeriesId: null,
      meeting: {
        meetingId: "meet-anarlog-0826",
        hasTranscript: true,
        hasNotes: true,
      },
    },
    {
      id: "evt-friday-0821",
      accountId: "google-work",
      title: "Friday review",
      dayOffset: -3,
      startHour: 13,
      startMinute: 0,
      durationMinutes: 60,
      recurringSeriesId: "series-friday-review",
      meeting: {
        meetingId: "meet-friday-0821",
        hasTranscript: true,
        hasNotes: true,
      },
    },
    {
      id: "evt-friday-0828",
      accountId: "google-work",
      title: "Friday review",
      dayOffset: 4,
      startHour: 13,
      startMinute: 0,
      durationMinutes: 60,
      recurringSeriesId: "series-friday-review",
      meeting: {
        meetingId: "meet-friday-0828",
        hasTranscript: true,
        hasNotes: true,
      },
    },
    {
      id: "evt-dentist-0827",
      accountId: "google-personal",
      title: "Dentist",
      dayOffset: 3,
      startHour: 11,
      startMinute: 0,
      durationMinutes: 60,
      recurringSeriesId: null,
      meeting: null,
    },
    {
      id: "evt-ep-master-0828",
      accountId: "google-personal",
      title: "Mix review — EP master",
      dayOffset: 4,
      startHour: 17,
      startMinute: 0,
      durationMinutes: 90,
      recurringSeriesId: null,
      meeting: {
        meetingId: "meet-ep-master-0828",
        hasTranscript: true,
        hasNotes: true,
      },
    },
  ],
  contextSnippets: [
    {
      id: "ctx-meet-standup-0824-d0",
      sourceTitle: "Daily standup",
      sourceKind: "meeting",
      sourceDate: "2026-08-24",
      excerpt: "Decision: The review board's columns mirror the engine's states one to one: Queue, Reviewing, Waiting external, Approved, Not approved.",
      score: 0.95,
    },
    {
      id: "ctx-meet-standup-0825-d0",
      sourceTitle: "Daily standup",
      sourceKind: "meeting",
      sourceDate: "2026-08-25",
      excerpt: "Decision: Web panel fixtures are generated from the seed scenario instead of being hand-maintained beside it.",
      score: 0.91,
    },
    {
      id: "ctx-meet-standup-0827-d0",
      sourceTitle: "Ежедневный статус",
      sourceKind: "meeting",
      sourceDate: "2026-08-27",
      excerpt: "Decision: Неизвестная схема базы Anarlog переводит коннектор в markdown-фолбэк со статусом awaiting-update, а не в ошибку.",
      score: 0.87,
    },
    {
      id: "ctx-meet-review-engine-0825-d0",
      sourceTitle: "Review engine deep dive",
      sourceKind: "meeting",
      sourceDate: "2026-08-25",
      excerpt: "Decision: Approving a review requires a repo playbook and at least one piece of runtime evidence; either missing caps the verdict at not approved.",
      score: 0.83,
    },
    {
      id: "ctx-meet-review-engine-0825-d1",
      sourceTitle: "Review engine deep dive",
      sourceKind: "meeting",
      sourceDate: "2026-08-25",
      excerpt: "Decision: External posting of verdicts stays opt-in and defaults to off; verdicts are local until the user approves posting.",
      score: 0.79,
    },
    {
      id: "ctx-meet-anarlog-0826-d0",
      sourceTitle: "Anarlog connector integration",
      sourceKind: "meeting",
      sourceDate: "2026-08-26",
      excerpt: "Decision: An ambiguous transcript-to-event match is surfaced for confirmation instead of being guessed.",
      score: 0.75,
    },
    {
      id: "ctx-meet-friday-0821-d0",
      sourceTitle: "Friday review",
      sourceKind: "meeting",
      sourceDate: "2026-08-21",
      excerpt: "Decision: Nomior migrations track in their own migration tables so upstream migration ids never collide with ours.",
      score: 0.71,
    },
    {
      id: "ctx-meet-friday-0828-d0",
      sourceTitle: "Friday review",
      sourceKind: "meeting",
      sourceDate: "2026-08-28",
      excerpt: "Decision: The scheduler stays credential-free: its only input is the rate-limit events the provider CLIs already emit — no keychain, no provider home directories, no usage polling.",
      score: 0.67,
    },
    {
      id: "ctx-meet-friday-0828-d1",
      sourceTitle: "Friday review",
      sourceKind: "meeting",
      sourceDate: "2026-08-28",
      excerpt: "Decision: A seeded scenario plus a simulation harness is the acceptance surface for the merged tracks: no demo without a passing simulation.",
      score: 0.63,
    },
    {
      id: "ctx-meet-ep-master-0828-d0",
      sourceTitle: "Mix review — EP master",
      sourceKind: "meeting",
      sourceDate: "2026-08-28",
      excerpt: "Decision: Ship the EP with the re-limited quieter master and keep the ISRC codes already registered with the distributor.",
      score: 0.59,
    },
    {
      id: "ctx-rev-104-f0",
      sourceTitle: "Review #96 — feat(catalog): ISRC dedupe pass over delivery feeds",
      sourceKind: "memory",
      sourceDate: "2026-08-29",
      excerpt: "Finding (critical): The dedupe pass deletes delivery rows before the new ISRC mapping commits; a failed commit loses catalogue rows with no way back. — apps/server/src/catalog/isrcDedupe.ts:214",
      score: 0.55,
    },
    {
      id: "ctx-rev-106-f0",
      sourceTitle: "Review #379 — feat(agents): unattended portfolio rebalancer",
      sourceKind: "memory",
      sourceDate: "2026-08-28",
      excerpt: "Finding (critical): Live orders are placed when dryRun is unset: the flag defaults to undefined, which is falsy, not to true. — apps/server/src/agents/rebalancer.ts:132",
      score: 0.51,
    },
    {
      id: "ctx-rev-106-f1",
      sourceTitle: "Review #379 — feat(agents): unattended portfolio rebalancer",
      sourceKind: "memory",
      sourceDate: "2026-08-28",
      excerpt: "Finding (critical): Broker credentials are read from the environment and written into the retry log alongside the request payload. — apps/server/src/agents/rebalancer.ts:288",
      score: 0.47,
    },
  ],
  memoryCandidates: [
    {
      id: "mem-501",
      text: "Ingest cursor writes must be idempotent: derive the cursor key from the batch id, never from wall-clock time, or a replayed batch double-advances the sync window.",
      source: "Review #388 — nomior-dev/nomior-invest",
      capturedAgoHours: 5,
    },
    {
      id: "mem-502",
      text: "Cards in the Waiting external column always name the human who owns the next step; a card with no owner is a queue with extra steps.",
      source: "Friday review — 2026-08-28",
      capturedAgoHours: 19.67,
    },
    {
      id: "mem-503",
      text: "Every automatic instance pick names its signal in user-facing copy: manual pin, project constraint, sticky, headroom, or rotation.",
      source: "PLAN.md — instance scheduler",
      capturedAgoHours: 45.92,
    },
  ],
  instances: [
    {
      id: "inst-claude-main",
      label: "Claude — main",
      provider: "Claude",
      health: "healthy",
      pinned: false,
      headroom: 0.72,
    },
    {
      id: "inst-claude-alt",
      label: "Claude — studio",
      provider: "Claude",
      health: "throttled",
      pinned: false,
      headroom: 0.06,
    },
    {
      id: "inst-codex-main",
      label: "Codex — main",
      provider: "Codex",
      health: "healthy",
      pinned: false,
      headroom: 0.55,
    },
    {
      id: "inst-grok",
      label: "Grok",
      provider: "Grok",
      health: "signed-out",
      pinned: false,
      headroom: null,
    },
  ],
  schedulerDecision: {
    instanceId: "inst-claude-main",
    reason: "Picked Claude — main: most rate-limit headroom (72%); Claude — studio is throttled until 18:00.",
    decidedAgoHours: 0.33,
  },
} as const;
